name: API CI - RealEstate

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test API en Node.js ${{ matrix.node }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [24.x]

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3
      
      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      
      - name: Instalar pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10
      
      - name: Cachear dependencias pnpm
        uses: actions/cache@v3
        with:
          path: |
            ~/.pnpm-store
            node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-
      
      - name: Instalar dependencias
        run: pnpm install
      
      - name: Ejecutar pruebas con Jest
        run: pnpm test
      
      - name: Reportar éxito
        if: success()
        run: echo "✅ API funcional en Node ${{ matrix.node }}"
      
      - name: Reportar error
        if: failure()
        run: echo "❌ Falla detectada en los tests para Node ${{ matrix.node }}"
